### ISSUE TITLE
GUI Overhaul

### ISSUE THREAD

**Issue by jhauerst** [Terrapin-Rocket-Team/Ground-Station#22]
## Description
The expanded feature set and use cases for the ground station have lead to a decrease in the usability of the GUI, and limit the possible addition of new features without workarounds or substantial changes to the current layout. Because of these issues, a new GUI design should be created that not only allows for improved usability of all current features, but also better allows for future expansion and modification. This issue should first involve the design of a new GUI that address the current issues, and conversations with software stakeholders about the new design, after which the implementation of the new GUI can take place. 

## Tasks
- [x] Design a new GUI that improves usability, allows for easy expansion, and meets the needs of stakeholders
- [x] Implement the new GUI design
- [x] Update relevant documentation
- [x] Develop and document an ability to test GUI functionality

## Notes
- This issue will likely supersede #8.
- The testing ability does not have to be programmatic. It can simply be a list of inputs and expected outputs.
- "Relevant documentation" is currently just the User Guide
