### ISSUE TITLE
Improved multiplexing

### ISSUE THREAD

**Issue by jhauerst** [Terrapin-Rocket-Team/Ground-Station#23]
## Description
The current multiplexing system is in need of improvement so that it is more robust for future use at the next Spaceport competition. The improved system should be able to handle a wider range of situations (e.g., different numbers/types of streams being available), and be more resilient to errors. It also will need to be able to handle an increased data rate, since the targeted bitrate of live video next year will be higher.

## Tasks
- [x] Develop and test the capability to handle a variable number of available streams
- [x] Improve error handling so that extraneous errors are caught (e.g., when video pipes are missing)
- [x] Improve muxing to increase usable bandwidth (currently only half of the available bandwidth is usable)

## Notes
- In terms of structure on the C++ side, it would be good to have a class that can be passed a header to create a new stream object that then looks for that header byte
- Errors thrown by missing named pipes are quite common, so we should probably develop a robust solution to handle these
- Ideally the serial driver should also be able to run on Linux, which would make it easier to develop a portable ground station hardware box

**Comment by jhauerst** [comment]
Getting the serial driver running on Linux has been added as #25.
