### ISSUE TITLE
Improve handling of communication with the radio

### ISSUE THREAD

**Issue by jhauerst** [Terrapin-Rocket-Team/Ground-Station#24]
## Description
While sufficient in the past, the current system for receiving and sending data from the radio is in need of improvement now that the Ground Station is handling multiple different types of data (video, telemetry, and commands). Basically we need a better way of parsing data, and then storing that data in a data structure so that it can be easily accessed in different parts of the application. Ideally this also includes some error handling that detects if the data was not in the expected format.

## Tasks
- [x] Examine how each type of data is encoded and whether this can change to make things easier somewhere in the processing chain
- [x] Develop a common structure for handling data on the JS backend between video, telemetry, and commands
- [x] Add error handling to JS data handling where possible
- [x] Find a better way to sync data handling between frontend and backend

## Notes
- This issue is related to #23, and changes made in both issues should complement each other where possible to improve the data handling process overall.
- The issue with syncing data handling on the frontend and backend is that currently there are two copies of the APRS.js file, one used by the backend with an extra line for module exports, and the other on the frontend without that line. Ideally one of these files can be removed and they can pull from the same source.
