### ISSUE TITLE
Serial driver Linux support

### ISSUE THREAD

**Issue by jhauerst** [Terrapin-Rocket-Team/Ground-Station#25]
## Description
The serial driver currently will only compile on Windows, since it relies on Windows specific header files. While this is expected, the serial driver should also be able to compile on Linux to support future uses of the Ground Station. So, an identical serial interface to the existing interface for the Windows serial port should be developed within the serial driver to allow for use on Linux. 

## Tasks
- [x] Update the serial port interface to work on Windows and Linux
- [x] Modify or extend the serial port interface as needed
- [x] Update build scripts as required

## Notes
The relevant files include ```serial/serialPort.hpp``` and ```serial/serialPort.cpp```.

**Comment by rk234** [comment]
Found a good guide on this [here](https://blog.mbedded.ninja/programming/operating-systems/linux/linux-serial-ports-using-c-cpp) and should be able to get it working soon.

**Comment by jhauerst** [comment]
Yeah it seems to be defined somewhere in ```windows.h```. I personally don't like using it so if you want to switch it out for ```unsigned char``` or ```uint8_t``` that's fine with me.

**Comment by rk234** [comment]
Got it, I plan on replacing them.
